### ISSUE TITLE
[ErrorException]  Undefined index: extra 

### ISSUE THREAD

**Issue by krewetka** [rubenrua/symfony-clean-tags-composer-plugin#4]
It got broken by recent symfony/symfony change

https://github.com/symfony/symfony/commit/5f1c3a797247a6d54992384df00bb22741fc1c34 there is no `extra` anymore.

It needs the same kind of fix as introduced here: https://github.com/zaporylie/composer-drupal-optimizations/pull/22/files

**Comment by rubenrua** [comment]
Thanks
